services:
  web:
    build: .
    container_name: guestbook_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./assets/uploads:/var/www/html/assets/uploads:cached
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - guestbook_network

  db:
    image: mysql:8.0
    container_name: guestbook_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-init:/docker-entrypoint-initdb.d:ro
    networks:
      - guestbook_network

networks:
  guestbook_network:

volumes:
  db_data:
